<Project>
  <Import Project="$(MSBuildThisFileDirectory)..\..\Directory.Build.props" />

  <PropertyGroup>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    <NoWarn>$(NoWarn);IDE0073</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <ProGpuWpfMvpPackageVersion>0.1.0-preview.43</ProGpuWpfMvpPackageVersion>
    <RestorePackagesPath>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)../../artifacts/nuget/ProGPU.Wpf.MvpApp'))</RestorePackagesPath>
    <RestoreForce>true</RestoreForce>
    <RestoreForceEvaluate>true</RestoreForceEvaluate>
  </PropertyGroup>

  <Target Name="_ProGpuWpfMvpClearMutablePackageCache" BeforeTargets="Restore">
    <ItemGroup>
      <_ProGpuWpfMvpMutablePackageCache Include="$(RestorePackagesPath)/microsoft.dotnet.wpf.github/$(ProGpuWpfMvpPackageVersion)" />
      <_ProGpuWpfMvpMutablePackageCache Include="$(RestorePackagesPath)/microsoft.dotnet.wpf.github.debug/$(ProGpuWpfMvpPackageVersion)" />
      <_ProGpuWpfMvpMutablePackageCache Include="$(RestorePackagesPath)/progpu.wpf.sdk/$(ProGpuWpfMvpPackageVersion)" />
      <_ProGpuWpfMvpMutablePackageCache Include="$(RestorePackagesPath)/progpu.wpf/$(ProGpuWpfMvpPackageVersion)" />
      <_ProGpuWpfMvpMutablePackageCache Include="$(RestorePackagesPath)/progpu.backend/$(ProGpuWpfMvpPackageVersion)" />
      <_ProGpuWpfMvpMutablePackageCache Include="$(RestorePackagesPath)/progpu.scene/$(ProGpuWpfMvpPackageVersion)" />
      <_ProGpuWpfMvpMutablePackageCache Include="$(RestorePackagesPath)/progpu.vector/$(ProGpuWpfMvpPackageVersion)" />
      <_ProGpuWpfMvpMutablePackageCache Include="$(RestorePackagesPath)/progpu.text/$(ProGpuWpfMvpPackageVersion)" />
      <_ProGpuWpfMvpMutablePackageCache Include="$(RestorePackagesPath)/progpu.compute/$(ProGpuWpfMvpPackageVersion)" />
      <_ProGpuWpfMvpMutablePackageCache Include="$(RestorePackagesPath)/progpu.transpiler/$(ProGpuWpfMvpPackageVersion)" />
      <_ProGpuWpfMvpExistingMutablePackageCache Include="@(_ProGpuWpfMvpMutablePackageCache)" Condition="Exists('%(_ProGpuWpfMvpMutablePackageCache.Identity)')" />
    </ItemGroup>

    <RemoveDir Directories="@(_ProGpuWpfMvpExistingMutablePackageCache)" />
  </Target>
</Project>
