<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;net10.0</TargetFrameworks>
    <AssemblyName>csp</AssemblyName>
    <OutputType>exe</OutputType>
    <PlatformTarget Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'">x86</PlatformTarget>
    <EnableDefaultItems>false</EnableDefaultItems>
    <StartupObject>MS.Internal.Csp.MainClass</StartupObject>
    <NoWarn>$(NoWarn);CA1051;CA1311;CA1845;SYSLIB1045</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <RuntimeFrameworkVersion>10.0.5</RuntimeFrameworkVersion>
    <UseOOBNETCoreAppTargetingPack>false</UseOOBNETCoreAppTargetingPack>
    <UseOOBNETCoreAppRuntimePack>false</UseOOBNETCoreAppRuntimePack>
    <UseOOBNETCoreAppAppHostPack>false</UseOOBNETCoreAppAppHostPack>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
  	<Compile Include="GlobalUsings.cs" />
    <Compile Include="MainClass.cs" />
    <Compile Include="Project.cs" />
    <Compile Include="TempDirectory.cs" />
    <Compile Include="CsPrimeParser.cs" />
    <Compile Include="CsPrimeRuntime.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System" Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'" />
    <Reference Include="System.Windows.Forms" Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="$(MicrosoftCodeAnalysisCSharpPackageVersion)" Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp'" PrivateAssets="all" />
  </ItemGroup>

</Project>
