<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.targets', '$(MSBuildThisFileDirectory)../'))" />

  <PropertyGroup>
    <VersionPrefix Condition="'$(PackageVersion)' == '0.1.0-preview.44'">0.1.0</VersionPrefix>
    <VersionSuffix Condition="'$(PackageVersion)' == '0.1.0-preview.44'">preview.44</VersionSuffix>
    <Version Condition="'$(Version)' != '$(PackageVersion)' And '$(PackageVersion)' != ''">$(PackageVersion)</Version>
  </PropertyGroup>
</Project>
