<Project Sdk="LibreWPF.Sdk/0.1.0-preview.45">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>$(ProGpuWpfSdkSampleTargetFramework)</TargetFramework>
    <UseWPF>true</UseWPF>
    <XceedPaidToolkitPackageVersion>5.2.26322.8434</XceedPaidToolkitPackageVersion>
    <XceedPaidDataGridPackageVersion>7.3.26322.8481</XceedPaidDataGridPackageVersion>
    <XceedPaidSystemDataSqlClientPackageVersion>4.9.1</XceedPaidSystemDataSqlClientPackageVersion>
    <XceedPaidSystemDrawingCommonPackageVersion>10.0.10</XceedPaidSystemDrawingCommonPackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Xceed.Wpf.Toolkit" Version="$(XceedPaidToolkitPackageVersion)" />
    <PackageReference Include="Xceed.Wpf.AvalonDock" Version="$(XceedPaidToolkitPackageVersion)" />
    <PackageReference Include="Xceed.Wpf.AvalonDock.Themes.Windows10" Version="$(XceedPaidToolkitPackageVersion)" />
    <PackageReference Include="Xceed.Wpf.Themes.Windows10" Version="$(XceedPaidToolkitPackageVersion)" />
    <PackageReference Include="Xceed.Wpf.Toolkit.Themes.MaterialDesign" Version="$(XceedPaidToolkitPackageVersion)" />
    <PackageReference Include="Xceed.Products.Wpf.DataGrid.Full" Version="$(XceedPaidDataGridPackageVersion)" />
    <PackageReference Include="System.Data.SqlClient" Version="$(XceedPaidSystemDataSqlClientPackageVersion)" />
    <PackageReference Include="System.Drawing.Common" Version="$(XceedPaidSystemDrawingCommonPackageVersion)" />
  </ItemGroup>
</Project>
