<Project>
  <Import Project="$(MSBuildThisFileDirectory)..\..\Directory.Build.props" />

  <PropertyGroup>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    <NoWarn>$(NoWarn);IDE0073</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <ProGpuWpfSciChartPackageVersion>0.1.0-preview.43</ProGpuWpfSciChartPackageVersion>
    <RestorePackagesPath>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)../../artifacts/nuget/ProGPU.Wpf.SciChartMvpApp'))</RestorePackagesPath>
    <RestoreForce>true</RestoreForce>
    <RestoreForceEvaluate>true</RestoreForceEvaluate>
  </PropertyGroup>

  <Target Name="_ProGpuWpfSciChartClearMutablePackageCache" BeforeTargets="Restore">
    <ItemGroup>
      <_ProGpuWpfSciChartMutablePackageCache Include="$(RestorePackagesPath)/microsoft.dotnet.wpf.github/$(ProGpuWpfSciChartPackageVersion)" />
      <_ProGpuWpfSciChartMutablePackageCache Include="$(RestorePackagesPath)/microsoft.dotnet.wpf.github.debug/$(ProGpuWpfSciChartPackageVersion)" />
      <_ProGpuWpfSciChartMutablePackageCache Include="$(RestorePackagesPath)/progpu.wpf.sdk/$(ProGpuWpfSciChartPackageVersion)" />
      <_ProGpuWpfSciChartMutablePackageCache Include="$(RestorePackagesPath)/progpu.wpf/$(ProGpuWpfSciChartPackageVersion)" />
      <_ProGpuWpfSciChartMutablePackageCache Include="$(RestorePackagesPath)/progpu.backend/$(ProGpuWpfSciChartPackageVersion)" />
      <_ProGpuWpfSciChartMutablePackageCache Include="$(RestorePackagesPath)/progpu.directx/$(ProGpuWpfSciChartPackageVersion)" />
      <_ProGpuWpfSciChartMutablePackageCache Include="$(RestorePackagesPath)/progpu.scene/$(ProGpuWpfSciChartPackageVersion)" />
      <_ProGpuWpfSciChartMutablePackageCache Include="$(RestorePackagesPath)/progpu.vector/$(ProGpuWpfSciChartPackageVersion)" />
      <_ProGpuWpfSciChartMutablePackageCache Include="$(RestorePackagesPath)/progpu.text/$(ProGpuWpfSciChartPackageVersion)" />
      <_ProGpuWpfSciChartMutablePackageCache Include="$(RestorePackagesPath)/progpu.compute/$(ProGpuWpfSciChartPackageVersion)" />
      <_ProGpuWpfSciChartMutablePackageCache Include="$(RestorePackagesPath)/progpu.transpiler/$(ProGpuWpfSciChartPackageVersion)" />
      <_ProGpuWpfSciChartExistingMutablePackageCache Include="@(_ProGpuWpfSciChartMutablePackageCache)" Condition="Exists('%(_ProGpuWpfSciChartMutablePackageCache.Identity)')" />
    </ItemGroup>

    <RemoveDir Directories="@(_ProGpuWpfSciChartExistingMutablePackageCache)" />
  </Target>
</Project>
